### ISSUE TITLE
Output directory won't be created if it doesn't exist

### ISSUE THREAD

**Issue by WarstekHUN** [christophe77/jest-coverage-badges-ts#2]
My NPM script is this:
`jest-coverage-badges-ts --output \"./.coverage-badges\"`

Altough the package's README says that <q><i>If output path doesn't exist it will be created</i></q> this is not true.
Error:
```
node:internal/fs/utils:350
    throw err;
    ^

Error: ENOENT: no such file or directory, open './.coverage-badges/badge-lines.svg'
    at Object.openSync (node:fs:603:3)
    at Object.writeFileSync (node:fs:2324:35)
    at IncomingMessage.<anonymous> (C:\[...]\node_modules\jest-coverage-badges-ts\dist\functions.js:49:26)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './.coverage-badges/badge-lines.svg'
}
```

**Comment by christophe77** [comment]
Can you try with :
jest-coverage-badges-ts --output \"./coverage-badges"

**Comment by WarstekHUN** [comment]
> Can you try with : jest-coverage-badges-ts --output "./coverage-badges"

Thanks for the fast reply!

I got the same error:
```
node:internal/fs/utils:350
    throw err;
    ^

Error: ENOENT: no such file or directory, open './coverage-badges/badge-lines.svg'
    at Object.openSync (node:fs:603:3)
    at Object.writeFileSync (node:fs:2324:35)
    at IncomingMessage.<anonymous> (C:\[...]\node_modules\jest-coverage-badges-ts\dist\functions.js:49:26)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: './coverage-badges/badge-lines.svg'
}
```

I also tried ` jest-coverage-badges-ts --output "coverage-badges"`. It did not work either.

**Comment by christophe77** [comment]
Ok I'll check this afternoon

**Comment by christophe77** [comment]
You can update to 0.1.8. And tell me if it's better.

**Comment by WarstekHUN** [comment]
It works now, many thanks!
